openapi: 3.0.0
info:
  title: Weekday Calculator
  description: Simple API to get a weekday n days from today
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Localhost for testing
paths:
  